### ISSUE TITLE
Create the views for the "events" app

### ISSUE THREAD

**Issue by SaltyQuetzals** [aggie-coding-club/club-website#67]
Creating, deleting, and modifying events should be handled through the django-admin page, which already has built-in staff permissions. No sense in re-inventing the wheel there, since nobody but staff will see it.

Thus, the only views we need are [read-only](http://www.django-rest-framework.org/api-guide/viewsets/#readonlymodelviewset).

We'll need to be able to:
- List all _current_ `Event`s (of any type)
- List _all_ `Event`s (of any type)

It'd be ideal if we could get `Event`s, `SponsoredEvent`s, and `WorkshopEvent`s all in one `Viewset`, though I anticipate that probably won't be easy.

**Comment by edgar-martinez** [comment]
@SaltyQuetzals, I found [this](https://django-rest-multiple-models.readthedocs.io/en/latest/basic-usage.html) regarding different models on the same `Viewset`. Flat or Nested JSON?

**Comment by SaltyQuetzals** [comment]
@edgar-martinez Flat models looks closer to the output I was envisioning.

**Comment by edgar-martinez** [comment]
Also, I'm assuming we'd want `SponsoredWorkshopEvent`s in there too.

**Comment by SaltyQuetzals** [comment]
Yep!
