### ISSUE TITLE
"Project Sign Ups" button does nothing

### ISSUE THREAD

**Issue by Jake3231** [aggie-coding-club/club-website#76]
**Describe the bug**
The "PROJECT SIGN UPS" button at the top right of the homepage appears to do nothing.

**To Reproduce**
1. Navigate to `http://aggiecodingclub.com` in your browser.
2. Click the "PROJECT SIGN UPS" button at the top right corner of the webpage.
3. Observe that nothing appears to happen, other than that your browser has navigated to `http://aggiecodingclub.com/#`

**Expected behavior**
Upon completing the above steps, the page should present some way to sign up for projects, at least from the user's perspective.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5 (18F132)
 - Browser: Safari
 - Version: 12.1.1

**Smartphone (please complete the following information):**
N/A

**Comment by SaltyQuetzals** [comment]
As project signup has not occurred for Fall 2019, the button is a no-op for now, though we should disable it.

**Comment by Jake3231** [comment]
Thanks for clarifying that. Just to make it more clear to the user, I’d suggest that the button either be or disabled or be set to trigger a dialog explaining that signup is unavailable.
